name: cvapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.8
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.8
  speech_to_text: ^6.6.2
  permission_handler: ^12.0.1
  provider: ^6.0.5
  lottie: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  golden_toolkit: ^0.15.0
  cloud_firestore_mocks: ^0.4.0
  mockito: ^5.4.0


flutter:
  uses-material-design: true

  assets:
    - assets/logo.jpg
    - assets/google_icon.png
    - assets/lottie/ai_processing.json